on:
  push:
    branches:
      
name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
        token: ${{ secrets.VRPACKAGETOKEN }}

    - name: Create version
      uses: ./
      with:
        script: './build.sh'
        commit_message: 'New Version: :new_version'
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        

